version: '3.9'

services:
  web:
    container_name: portfolio
    build:
      dockerfile: Dockerfile
      context: ./React-portfolio
    ports:
      - "3000:3000"
    volumes:
      - ./React-portfolio:/app
    command: npm start