version: '3.9'

services:
  web:
    container_name: portfolio
    build:
      dockerfile: Dockerfile
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    command: npm start